/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangCompleteProfileRouteImport } from './routes/$lang/complete-profile'
import { Route as LangAuthRouteImport } from './routes/$lang/auth'
import { Route as LangAuthenticatedRouteImport } from './routes/$lang/_authenticated'
import { Route as LangNotFoundRouteImport } from './routes/$lang/$notFound'
import { Route as LangAuthenticatedOwnerRouteRouteImport } from './routes/$lang/_authenticated/owner/route'
import { Route as LangAuthenticatedFreelancerRouteRouteImport } from './routes/$lang/_authenticated/freelancer/route'
import { Route as LangAuthenticatedAdminRouteRouteImport } from './routes/$lang/_authenticated/admin/route'
import { Route as LangAuthenticatedOwnerIndexRouteImport } from './routes/$lang/_authenticated/owner/index'
import { Route as LangAuthenticatedFreelancerIndexRouteImport } from './routes/$lang/_authenticated/freelancer/index'
import { Route as LangAuthenticatedAdminIndexRouteImport } from './routes/$lang/_authenticated/admin/index'
import { Route as LangAuthenticatedOwnerDashboardRouteImport } from './routes/$lang/_authenticated/owner/dashboard'
import { Route as LangAuthenticatedFreelancerDashboardRouteImport } from './routes/$lang/_authenticated/freelancer/dashboard'
import { Route as LangAuthenticatedAdminDashboardRouteImport } from './routes/$lang/_authenticated/admin/dashboard'
import { Route as LangAuthenticatedOwnerProjectsIndexRouteImport } from './routes/$lang/_authenticated/owner/projects/index'
import { Route as LangAuthenticatedOwnerProjectsIdRouteImport } from './routes/$lang/_authenticated/owner/projects/$id'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangCompleteProfileRoute = LangCompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => LangRoute,
} as any)
const LangAuthRoute = LangAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => LangRoute,
} as any)
const LangAuthenticatedRoute = LangAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LangRoute,
} as any)
const LangNotFoundRoute = LangNotFoundRouteImport.update({
  id: '/$notFound',
  path: '/$notFound',
  getParentRoute: () => LangRoute,
} as any)
const LangAuthenticatedOwnerRouteRoute =
  LangAuthenticatedOwnerRouteRouteImport.update({
    id: '/owner',
    path: '/owner',
    getParentRoute: () => LangAuthenticatedRoute,
  } as any)
const LangAuthenticatedFreelancerRouteRoute =
  LangAuthenticatedFreelancerRouteRouteImport.update({
    id: '/freelancer',
    path: '/freelancer',
    getParentRoute: () => LangAuthenticatedRoute,
  } as any)
const LangAuthenticatedAdminRouteRoute =
  LangAuthenticatedAdminRouteRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => LangAuthenticatedRoute,
  } as any)
const LangAuthenticatedOwnerIndexRoute =
  LangAuthenticatedOwnerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LangAuthenticatedOwnerRouteRoute,
  } as any)
const LangAuthenticatedFreelancerIndexRoute =
  LangAuthenticatedFreelancerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LangAuthenticatedFreelancerRouteRoute,
  } as any)
const LangAuthenticatedAdminIndexRoute =
  LangAuthenticatedAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LangAuthenticatedAdminRouteRoute,
  } as any)
const LangAuthenticatedOwnerDashboardRoute =
  LangAuthenticatedOwnerDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LangAuthenticatedOwnerRouteRoute,
  } as any)
const LangAuthenticatedFreelancerDashboardRoute =
  LangAuthenticatedFreelancerDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LangAuthenticatedFreelancerRouteRoute,
  } as any)
const LangAuthenticatedAdminDashboardRoute =
  LangAuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LangAuthenticatedAdminRouteRoute,
  } as any)
const LangAuthenticatedOwnerProjectsIndexRoute =
  LangAuthenticatedOwnerProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => LangAuthenticatedOwnerRouteRoute,
  } as any)
const LangAuthenticatedOwnerProjectsIdRoute =
  LangAuthenticatedOwnerProjectsIdRouteImport.update({
    id: '/projects/$id',
    path: '/projects/$id',
    getParentRoute: () => LangAuthenticatedOwnerRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangAuthenticatedRouteWithChildren
  '/$lang/$notFound': typeof LangNotFoundRoute
  '/$lang/auth': typeof LangAuthRoute
  '/$lang/complete-profile': typeof LangCompleteProfileRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/admin': typeof LangAuthenticatedAdminRouteRouteWithChildren
  '/$lang/freelancer': typeof LangAuthenticatedFreelancerRouteRouteWithChildren
  '/$lang/owner': typeof LangAuthenticatedOwnerRouteRouteWithChildren
  '/$lang/admin/dashboard': typeof LangAuthenticatedAdminDashboardRoute
  '/$lang/freelancer/dashboard': typeof LangAuthenticatedFreelancerDashboardRoute
  '/$lang/owner/dashboard': typeof LangAuthenticatedOwnerDashboardRoute
  '/$lang/admin/': typeof LangAuthenticatedAdminIndexRoute
  '/$lang/freelancer/': typeof LangAuthenticatedFreelancerIndexRoute
  '/$lang/owner/': typeof LangAuthenticatedOwnerIndexRoute
  '/$lang/owner/projects/$id': typeof LangAuthenticatedOwnerProjectsIdRoute
  '/$lang/owner/projects': typeof LangAuthenticatedOwnerProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/$notFound': typeof LangNotFoundRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/auth': typeof LangAuthRoute
  '/$lang/complete-profile': typeof LangCompleteProfileRoute
  '/$lang/admin/dashboard': typeof LangAuthenticatedAdminDashboardRoute
  '/$lang/freelancer/dashboard': typeof LangAuthenticatedFreelancerDashboardRoute
  '/$lang/owner/dashboard': typeof LangAuthenticatedOwnerDashboardRoute
  '/$lang/admin': typeof LangAuthenticatedAdminIndexRoute
  '/$lang/freelancer': typeof LangAuthenticatedFreelancerIndexRoute
  '/$lang/owner': typeof LangAuthenticatedOwnerIndexRoute
  '/$lang/owner/projects/$id': typeof LangAuthenticatedOwnerProjectsIdRoute
  '/$lang/owner/projects': typeof LangAuthenticatedOwnerProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/$notFound': typeof LangNotFoundRoute
  '/$lang/_authenticated': typeof LangAuthenticatedRouteWithChildren
  '/$lang/auth': typeof LangAuthRoute
  '/$lang/complete-profile': typeof LangCompleteProfileRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/_authenticated/admin': typeof LangAuthenticatedAdminRouteRouteWithChildren
  '/$lang/_authenticated/freelancer': typeof LangAuthenticatedFreelancerRouteRouteWithChildren
  '/$lang/_authenticated/owner': typeof LangAuthenticatedOwnerRouteRouteWithChildren
  '/$lang/_authenticated/admin/dashboard': typeof LangAuthenticatedAdminDashboardRoute
  '/$lang/_authenticated/freelancer/dashboard': typeof LangAuthenticatedFreelancerDashboardRoute
  '/$lang/_authenticated/owner/dashboard': typeof LangAuthenticatedOwnerDashboardRoute
  '/$lang/_authenticated/admin/': typeof LangAuthenticatedAdminIndexRoute
  '/$lang/_authenticated/freelancer/': typeof LangAuthenticatedFreelancerIndexRoute
  '/$lang/_authenticated/owner/': typeof LangAuthenticatedOwnerIndexRoute
  '/$lang/_authenticated/owner/projects/$id': typeof LangAuthenticatedOwnerProjectsIdRoute
  '/$lang/_authenticated/owner/projects/': typeof LangAuthenticatedOwnerProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/$notFound'
    | '/$lang/auth'
    | '/$lang/complete-profile'
    | '/$lang/'
    | '/$lang/admin'
    | '/$lang/freelancer'
    | '/$lang/owner'
    | '/$lang/admin/dashboard'
    | '/$lang/freelancer/dashboard'
    | '/$lang/owner/dashboard'
    | '/$lang/admin/'
    | '/$lang/freelancer/'
    | '/$lang/owner/'
    | '/$lang/owner/projects/$id'
    | '/$lang/owner/projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/$notFound'
    | '/$lang'
    | '/$lang/auth'
    | '/$lang/complete-profile'
    | '/$lang/admin/dashboard'
    | '/$lang/freelancer/dashboard'
    | '/$lang/owner/dashboard'
    | '/$lang/admin'
    | '/$lang/freelancer'
    | '/$lang/owner'
    | '/$lang/owner/projects/$id'
    | '/$lang/owner/projects'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/$notFound'
    | '/$lang/_authenticated'
    | '/$lang/auth'
    | '/$lang/complete-profile'
    | '/$lang/'
    | '/$lang/_authenticated/admin'
    | '/$lang/_authenticated/freelancer'
    | '/$lang/_authenticated/owner'
    | '/$lang/_authenticated/admin/dashboard'
    | '/$lang/_authenticated/freelancer/dashboard'
    | '/$lang/_authenticated/owner/dashboard'
    | '/$lang/_authenticated/admin/'
    | '/$lang/_authenticated/freelancer/'
    | '/$lang/_authenticated/owner/'
    | '/$lang/_authenticated/owner/projects/$id'
    | '/$lang/_authenticated/owner/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/complete-profile': {
      id: '/$lang/complete-profile'
      path: '/complete-profile'
      fullPath: '/$lang/complete-profile'
      preLoaderRoute: typeof LangCompleteProfileRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/auth': {
      id: '/$lang/auth'
      path: '/auth'
      fullPath: '/$lang/auth'
      preLoaderRoute: typeof LangAuthRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_authenticated': {
      id: '/$lang/_authenticated'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangAuthenticatedRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/$notFound': {
      id: '/$lang/$notFound'
      path: '/$notFound'
      fullPath: '/$lang/$notFound'
      preLoaderRoute: typeof LangNotFoundRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_authenticated/owner': {
      id: '/$lang/_authenticated/owner'
      path: '/owner'
      fullPath: '/$lang/owner'
      preLoaderRoute: typeof LangAuthenticatedOwnerRouteRouteImport
      parentRoute: typeof LangAuthenticatedRoute
    }
    '/$lang/_authenticated/freelancer': {
      id: '/$lang/_authenticated/freelancer'
      path: '/freelancer'
      fullPath: '/$lang/freelancer'
      preLoaderRoute: typeof LangAuthenticatedFreelancerRouteRouteImport
      parentRoute: typeof LangAuthenticatedRoute
    }
    '/$lang/_authenticated/admin': {
      id: '/$lang/_authenticated/admin'
      path: '/admin'
      fullPath: '/$lang/admin'
      preLoaderRoute: typeof LangAuthenticatedAdminRouteRouteImport
      parentRoute: typeof LangAuthenticatedRoute
    }
    '/$lang/_authenticated/owner/': {
      id: '/$lang/_authenticated/owner/'
      path: '/'
      fullPath: '/$lang/owner/'
      preLoaderRoute: typeof LangAuthenticatedOwnerIndexRouteImport
      parentRoute: typeof LangAuthenticatedOwnerRouteRoute
    }
    '/$lang/_authenticated/freelancer/': {
      id: '/$lang/_authenticated/freelancer/'
      path: '/'
      fullPath: '/$lang/freelancer/'
      preLoaderRoute: typeof LangAuthenticatedFreelancerIndexRouteImport
      parentRoute: typeof LangAuthenticatedFreelancerRouteRoute
    }
    '/$lang/_authenticated/admin/': {
      id: '/$lang/_authenticated/admin/'
      path: '/'
      fullPath: '/$lang/admin/'
      preLoaderRoute: typeof LangAuthenticatedAdminIndexRouteImport
      parentRoute: typeof LangAuthenticatedAdminRouteRoute
    }
    '/$lang/_authenticated/owner/dashboard': {
      id: '/$lang/_authenticated/owner/dashboard'
      path: '/dashboard'
      fullPath: '/$lang/owner/dashboard'
      preLoaderRoute: typeof LangAuthenticatedOwnerDashboardRouteImport
      parentRoute: typeof LangAuthenticatedOwnerRouteRoute
    }
    '/$lang/_authenticated/freelancer/dashboard': {
      id: '/$lang/_authenticated/freelancer/dashboard'
      path: '/dashboard'
      fullPath: '/$lang/freelancer/dashboard'
      preLoaderRoute: typeof LangAuthenticatedFreelancerDashboardRouteImport
      parentRoute: typeof LangAuthenticatedFreelancerRouteRoute
    }
    '/$lang/_authenticated/admin/dashboard': {
      id: '/$lang/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/$lang/admin/dashboard'
      preLoaderRoute: typeof LangAuthenticatedAdminDashboardRouteImport
      parentRoute: typeof LangAuthenticatedAdminRouteRoute
    }
    '/$lang/_authenticated/owner/projects/': {
      id: '/$lang/_authenticated/owner/projects/'
      path: '/projects'
      fullPath: '/$lang/owner/projects'
      preLoaderRoute: typeof LangAuthenticatedOwnerProjectsIndexRouteImport
      parentRoute: typeof LangAuthenticatedOwnerRouteRoute
    }
    '/$lang/_authenticated/owner/projects/$id': {
      id: '/$lang/_authenticated/owner/projects/$id'
      path: '/projects/$id'
      fullPath: '/$lang/owner/projects/$id'
      preLoaderRoute: typeof LangAuthenticatedOwnerProjectsIdRouteImport
      parentRoute: typeof LangAuthenticatedOwnerRouteRoute
    }
  }
}

interface LangAuthenticatedAdminRouteRouteChildren {
  LangAuthenticatedAdminDashboardRoute: typeof LangAuthenticatedAdminDashboardRoute
  LangAuthenticatedAdminIndexRoute: typeof LangAuthenticatedAdminIndexRoute
}

const LangAuthenticatedAdminRouteRouteChildren: LangAuthenticatedAdminRouteRouteChildren =
  {
    LangAuthenticatedAdminDashboardRoute: LangAuthenticatedAdminDashboardRoute,
    LangAuthenticatedAdminIndexRoute: LangAuthenticatedAdminIndexRoute,
  }

const LangAuthenticatedAdminRouteRouteWithChildren =
  LangAuthenticatedAdminRouteRoute._addFileChildren(
    LangAuthenticatedAdminRouteRouteChildren,
  )

interface LangAuthenticatedFreelancerRouteRouteChildren {
  LangAuthenticatedFreelancerDashboardRoute: typeof LangAuthenticatedFreelancerDashboardRoute
  LangAuthenticatedFreelancerIndexRoute: typeof LangAuthenticatedFreelancerIndexRoute
}

const LangAuthenticatedFreelancerRouteRouteChildren: LangAuthenticatedFreelancerRouteRouteChildren =
  {
    LangAuthenticatedFreelancerDashboardRoute:
      LangAuthenticatedFreelancerDashboardRoute,
    LangAuthenticatedFreelancerIndexRoute:
      LangAuthenticatedFreelancerIndexRoute,
  }

const LangAuthenticatedFreelancerRouteRouteWithChildren =
  LangAuthenticatedFreelancerRouteRoute._addFileChildren(
    LangAuthenticatedFreelancerRouteRouteChildren,
  )

interface LangAuthenticatedOwnerRouteRouteChildren {
  LangAuthenticatedOwnerDashboardRoute: typeof LangAuthenticatedOwnerDashboardRoute
  LangAuthenticatedOwnerIndexRoute: typeof LangAuthenticatedOwnerIndexRoute
  LangAuthenticatedOwnerProjectsIdRoute: typeof LangAuthenticatedOwnerProjectsIdRoute
  LangAuthenticatedOwnerProjectsIndexRoute: typeof LangAuthenticatedOwnerProjectsIndexRoute
}

const LangAuthenticatedOwnerRouteRouteChildren: LangAuthenticatedOwnerRouteRouteChildren =
  {
    LangAuthenticatedOwnerDashboardRoute: LangAuthenticatedOwnerDashboardRoute,
    LangAuthenticatedOwnerIndexRoute: LangAuthenticatedOwnerIndexRoute,
    LangAuthenticatedOwnerProjectsIdRoute:
      LangAuthenticatedOwnerProjectsIdRoute,
    LangAuthenticatedOwnerProjectsIndexRoute:
      LangAuthenticatedOwnerProjectsIndexRoute,
  }

const LangAuthenticatedOwnerRouteRouteWithChildren =
  LangAuthenticatedOwnerRouteRoute._addFileChildren(
    LangAuthenticatedOwnerRouteRouteChildren,
  )

interface LangAuthenticatedRouteChildren {
  LangAuthenticatedAdminRouteRoute: typeof LangAuthenticatedAdminRouteRouteWithChildren
  LangAuthenticatedFreelancerRouteRoute: typeof LangAuthenticatedFreelancerRouteRouteWithChildren
  LangAuthenticatedOwnerRouteRoute: typeof LangAuthenticatedOwnerRouteRouteWithChildren
}

const LangAuthenticatedRouteChildren: LangAuthenticatedRouteChildren = {
  LangAuthenticatedAdminRouteRoute:
    LangAuthenticatedAdminRouteRouteWithChildren,
  LangAuthenticatedFreelancerRouteRoute:
    LangAuthenticatedFreelancerRouteRouteWithChildren,
  LangAuthenticatedOwnerRouteRoute:
    LangAuthenticatedOwnerRouteRouteWithChildren,
}

const LangAuthenticatedRouteWithChildren =
  LangAuthenticatedRoute._addFileChildren(LangAuthenticatedRouteChildren)

interface LangRouteChildren {
  LangNotFoundRoute: typeof LangNotFoundRoute
  LangAuthenticatedRoute: typeof LangAuthenticatedRouteWithChildren
  LangAuthRoute: typeof LangAuthRoute
  LangCompleteProfileRoute: typeof LangCompleteProfileRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangNotFoundRoute: LangNotFoundRoute,
  LangAuthenticatedRoute: LangAuthenticatedRouteWithChildren,
  LangAuthRoute: LangAuthRoute,
  LangCompleteProfileRoute: LangCompleteProfileRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
