/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangCompleteProfileRouteImport } from './routes/$lang/complete-profile'
import { Route as LangAuthRouteImport } from './routes/$lang/auth'
import { Route as LangNotFoundRouteImport } from './routes/$lang/$notFound'
import { Route as LangOwnerRouteRouteImport } from './routes/$lang/owner/route'
import { Route as LangFreelancerRouteRouteImport } from './routes/$lang/freelancer/route'
import { Route as LangAdminRouteRouteImport } from './routes/$lang/admin/route'
import { Route as LangOwnerIndexRouteImport } from './routes/$lang/owner/index'
import { Route as LangFreelancerIndexRouteImport } from './routes/$lang/freelancer/index'
import { Route as LangAdminIndexRouteImport } from './routes/$lang/admin/index'
import { Route as LangOwnerDashboardRouteImport } from './routes/$lang/owner/dashboard'
import { Route as LangFreelancerDashboardRouteImport } from './routes/$lang/freelancer/dashboard'
import { Route as LangAdminDashboardRouteImport } from './routes/$lang/admin/dashboard'
import { Route as LangOwnerProjectsIndexRouteImport } from './routes/$lang/owner/projects/index'
import { Route as LangOwnerProjectsIdRouteImport } from './routes/$lang/owner/projects/$id'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangCompleteProfileRoute = LangCompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => LangRoute,
} as any)
const LangAuthRoute = LangAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => LangRoute,
} as any)
const LangNotFoundRoute = LangNotFoundRouteImport.update({
  id: '/$notFound',
  path: '/$notFound',
  getParentRoute: () => LangRoute,
} as any)
const LangOwnerRouteRoute = LangOwnerRouteRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => LangRoute,
} as any)
const LangFreelancerRouteRoute = LangFreelancerRouteRouteImport.update({
  id: '/freelancer',
  path: '/freelancer',
  getParentRoute: () => LangRoute,
} as any)
const LangAdminRouteRoute = LangAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LangRoute,
} as any)
const LangOwnerIndexRoute = LangOwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangOwnerRouteRoute,
} as any)
const LangFreelancerIndexRoute = LangFreelancerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangFreelancerRouteRoute,
} as any)
const LangAdminIndexRoute = LangAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangAdminRouteRoute,
} as any)
const LangOwnerDashboardRoute = LangOwnerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LangOwnerRouteRoute,
} as any)
const LangFreelancerDashboardRoute = LangFreelancerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LangFreelancerRouteRoute,
} as any)
const LangAdminDashboardRoute = LangAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LangAdminRouteRoute,
} as any)
const LangOwnerProjectsIndexRoute = LangOwnerProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => LangOwnerRouteRoute,
} as any)
const LangOwnerProjectsIdRoute = LangOwnerProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => LangOwnerRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/admin': typeof LangAdminRouteRouteWithChildren
  '/$lang/freelancer': typeof LangFreelancerRouteRouteWithChildren
  '/$lang/owner': typeof LangOwnerRouteRouteWithChildren
  '/$lang/$notFound': typeof LangNotFoundRoute
  '/$lang/auth': typeof LangAuthRoute
  '/$lang/complete-profile': typeof LangCompleteProfileRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/admin/dashboard': typeof LangAdminDashboardRoute
  '/$lang/freelancer/dashboard': typeof LangFreelancerDashboardRoute
  '/$lang/owner/dashboard': typeof LangOwnerDashboardRoute
  '/$lang/admin/': typeof LangAdminIndexRoute
  '/$lang/freelancer/': typeof LangFreelancerIndexRoute
  '/$lang/owner/': typeof LangOwnerIndexRoute
  '/$lang/owner/projects/$id': typeof LangOwnerProjectsIdRoute
  '/$lang/owner/projects': typeof LangOwnerProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/$notFound': typeof LangNotFoundRoute
  '/$lang/auth': typeof LangAuthRoute
  '/$lang/complete-profile': typeof LangCompleteProfileRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/admin/dashboard': typeof LangAdminDashboardRoute
  '/$lang/freelancer/dashboard': typeof LangFreelancerDashboardRoute
  '/$lang/owner/dashboard': typeof LangOwnerDashboardRoute
  '/$lang/admin': typeof LangAdminIndexRoute
  '/$lang/freelancer': typeof LangFreelancerIndexRoute
  '/$lang/owner': typeof LangOwnerIndexRoute
  '/$lang/owner/projects/$id': typeof LangOwnerProjectsIdRoute
  '/$lang/owner/projects': typeof LangOwnerProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/admin': typeof LangAdminRouteRouteWithChildren
  '/$lang/freelancer': typeof LangFreelancerRouteRouteWithChildren
  '/$lang/owner': typeof LangOwnerRouteRouteWithChildren
  '/$lang/$notFound': typeof LangNotFoundRoute
  '/$lang/auth': typeof LangAuthRoute
  '/$lang/complete-profile': typeof LangCompleteProfileRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/admin/dashboard': typeof LangAdminDashboardRoute
  '/$lang/freelancer/dashboard': typeof LangFreelancerDashboardRoute
  '/$lang/owner/dashboard': typeof LangOwnerDashboardRoute
  '/$lang/admin/': typeof LangAdminIndexRoute
  '/$lang/freelancer/': typeof LangFreelancerIndexRoute
  '/$lang/owner/': typeof LangOwnerIndexRoute
  '/$lang/owner/projects/$id': typeof LangOwnerProjectsIdRoute
  '/$lang/owner/projects/': typeof LangOwnerProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/admin'
    | '/$lang/freelancer'
    | '/$lang/owner'
    | '/$lang/$notFound'
    | '/$lang/auth'
    | '/$lang/complete-profile'
    | '/$lang/'
    | '/$lang/admin/dashboard'
    | '/$lang/freelancer/dashboard'
    | '/$lang/owner/dashboard'
    | '/$lang/admin/'
    | '/$lang/freelancer/'
    | '/$lang/owner/'
    | '/$lang/owner/projects/$id'
    | '/$lang/owner/projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/$notFound'
    | '/$lang/auth'
    | '/$lang/complete-profile'
    | '/$lang'
    | '/$lang/admin/dashboard'
    | '/$lang/freelancer/dashboard'
    | '/$lang/owner/dashboard'
    | '/$lang/admin'
    | '/$lang/freelancer'
    | '/$lang/owner'
    | '/$lang/owner/projects/$id'
    | '/$lang/owner/projects'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/admin'
    | '/$lang/freelancer'
    | '/$lang/owner'
    | '/$lang/$notFound'
    | '/$lang/auth'
    | '/$lang/complete-profile'
    | '/$lang/'
    | '/$lang/admin/dashboard'
    | '/$lang/freelancer/dashboard'
    | '/$lang/owner/dashboard'
    | '/$lang/admin/'
    | '/$lang/freelancer/'
    | '/$lang/owner/'
    | '/$lang/owner/projects/$id'
    | '/$lang/owner/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/complete-profile': {
      id: '/$lang/complete-profile'
      path: '/complete-profile'
      fullPath: '/$lang/complete-profile'
      preLoaderRoute: typeof LangCompleteProfileRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/auth': {
      id: '/$lang/auth'
      path: '/auth'
      fullPath: '/$lang/auth'
      preLoaderRoute: typeof LangAuthRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/$notFound': {
      id: '/$lang/$notFound'
      path: '/$notFound'
      fullPath: '/$lang/$notFound'
      preLoaderRoute: typeof LangNotFoundRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/owner': {
      id: '/$lang/owner'
      path: '/owner'
      fullPath: '/$lang/owner'
      preLoaderRoute: typeof LangOwnerRouteRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/freelancer': {
      id: '/$lang/freelancer'
      path: '/freelancer'
      fullPath: '/$lang/freelancer'
      preLoaderRoute: typeof LangFreelancerRouteRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/admin': {
      id: '/$lang/admin'
      path: '/admin'
      fullPath: '/$lang/admin'
      preLoaderRoute: typeof LangAdminRouteRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/owner/': {
      id: '/$lang/owner/'
      path: '/'
      fullPath: '/$lang/owner/'
      preLoaderRoute: typeof LangOwnerIndexRouteImport
      parentRoute: typeof LangOwnerRouteRoute
    }
    '/$lang/freelancer/': {
      id: '/$lang/freelancer/'
      path: '/'
      fullPath: '/$lang/freelancer/'
      preLoaderRoute: typeof LangFreelancerIndexRouteImport
      parentRoute: typeof LangFreelancerRouteRoute
    }
    '/$lang/admin/': {
      id: '/$lang/admin/'
      path: '/'
      fullPath: '/$lang/admin/'
      preLoaderRoute: typeof LangAdminIndexRouteImport
      parentRoute: typeof LangAdminRouteRoute
    }
    '/$lang/owner/dashboard': {
      id: '/$lang/owner/dashboard'
      path: '/dashboard'
      fullPath: '/$lang/owner/dashboard'
      preLoaderRoute: typeof LangOwnerDashboardRouteImport
      parentRoute: typeof LangOwnerRouteRoute
    }
    '/$lang/freelancer/dashboard': {
      id: '/$lang/freelancer/dashboard'
      path: '/dashboard'
      fullPath: '/$lang/freelancer/dashboard'
      preLoaderRoute: typeof LangFreelancerDashboardRouteImport
      parentRoute: typeof LangFreelancerRouteRoute
    }
    '/$lang/admin/dashboard': {
      id: '/$lang/admin/dashboard'
      path: '/dashboard'
      fullPath: '/$lang/admin/dashboard'
      preLoaderRoute: typeof LangAdminDashboardRouteImport
      parentRoute: typeof LangAdminRouteRoute
    }
    '/$lang/owner/projects/': {
      id: '/$lang/owner/projects/'
      path: '/projects'
      fullPath: '/$lang/owner/projects'
      preLoaderRoute: typeof LangOwnerProjectsIndexRouteImport
      parentRoute: typeof LangOwnerRouteRoute
    }
    '/$lang/owner/projects/$id': {
      id: '/$lang/owner/projects/$id'
      path: '/projects/$id'
      fullPath: '/$lang/owner/projects/$id'
      preLoaderRoute: typeof LangOwnerProjectsIdRouteImport
      parentRoute: typeof LangOwnerRouteRoute
    }
  }
}

interface LangAdminRouteRouteChildren {
  LangAdminDashboardRoute: typeof LangAdminDashboardRoute
  LangAdminIndexRoute: typeof LangAdminIndexRoute
}

const LangAdminRouteRouteChildren: LangAdminRouteRouteChildren = {
  LangAdminDashboardRoute: LangAdminDashboardRoute,
  LangAdminIndexRoute: LangAdminIndexRoute,
}

const LangAdminRouteRouteWithChildren = LangAdminRouteRoute._addFileChildren(
  LangAdminRouteRouteChildren,
)

interface LangFreelancerRouteRouteChildren {
  LangFreelancerDashboardRoute: typeof LangFreelancerDashboardRoute
  LangFreelancerIndexRoute: typeof LangFreelancerIndexRoute
}

const LangFreelancerRouteRouteChildren: LangFreelancerRouteRouteChildren = {
  LangFreelancerDashboardRoute: LangFreelancerDashboardRoute,
  LangFreelancerIndexRoute: LangFreelancerIndexRoute,
}

const LangFreelancerRouteRouteWithChildren =
  LangFreelancerRouteRoute._addFileChildren(LangFreelancerRouteRouteChildren)

interface LangOwnerRouteRouteChildren {
  LangOwnerDashboardRoute: typeof LangOwnerDashboardRoute
  LangOwnerIndexRoute: typeof LangOwnerIndexRoute
  LangOwnerProjectsIdRoute: typeof LangOwnerProjectsIdRoute
  LangOwnerProjectsIndexRoute: typeof LangOwnerProjectsIndexRoute
}

const LangOwnerRouteRouteChildren: LangOwnerRouteRouteChildren = {
  LangOwnerDashboardRoute: LangOwnerDashboardRoute,
  LangOwnerIndexRoute: LangOwnerIndexRoute,
  LangOwnerProjectsIdRoute: LangOwnerProjectsIdRoute,
  LangOwnerProjectsIndexRoute: LangOwnerProjectsIndexRoute,
}

const LangOwnerRouteRouteWithChildren = LangOwnerRouteRoute._addFileChildren(
  LangOwnerRouteRouteChildren,
)

interface LangRouteChildren {
  LangAdminRouteRoute: typeof LangAdminRouteRouteWithChildren
  LangFreelancerRouteRoute: typeof LangFreelancerRouteRouteWithChildren
  LangOwnerRouteRoute: typeof LangOwnerRouteRouteWithChildren
  LangNotFoundRoute: typeof LangNotFoundRoute
  LangAuthRoute: typeof LangAuthRoute
  LangCompleteProfileRoute: typeof LangCompleteProfileRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAdminRouteRoute: LangAdminRouteRouteWithChildren,
  LangFreelancerRouteRoute: LangFreelancerRouteRouteWithChildren,
  LangOwnerRouteRoute: LangOwnerRouteRouteWithChildren,
  LangNotFoundRoute: LangNotFoundRoute,
  LangAuthRoute: LangAuthRoute,
  LangCompleteProfileRoute: LangCompleteProfileRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
