name: format

on:
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.13.1
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - run: pnpm install
      - run: pnpm format
      - run: pnpm lint
